version: "3.8"
services:
  web:
    image: "httpd:2.4"
    ports:
      - "8080:80"
    volumes:
      - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./public-html/:/usr/local/apache2/htdocs/
      - ./cgi-bin/:/usr/local/apache2/cgi-bin/
      - ./assets/:/usr/local/apache2/assets/
